# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3779073ed932913febfe1761a5d1d91f9b7b917bbff7323e83a19b74dbf4978de0b494a80f10236dc32c4a3a2e9db6361a06b73ff5d4336fc8f77f983f28333

test:
  secret_key_base: 7552a1556d6a59b500157d00528d090023674d0c692b61a99b054439d0249df2d14f779821dd262c2003370ed9683a8a93863b4817750cbbf6bf8005f801d410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
